# sbatch --job-name=ushcn --output=/home/yalavarthi/seperable_flows/results/ushcn/ushcn-mnf-ct-36-ft-0-710-%A.log --error=/home/yalavarthi/seperable_flows/results/ushcn/ushcn-mnf-ct-36-ft-0-710-%A.err --mail-type=FAIL --mail-user=yalavarthi@ismll.de /home/yalavarthi/seperable_flows/sbatch_file.sh train_mnf.py --batch-size 64 --epochs 1000 -lr 0.001 --dataset ushcn --n-gaussians 5 --flayers 3 --n-heads 4 --encoder grafiti --enc-layers 3 --n-hidden 128 -ct 36 -ft 0 --fold 0 
# sbatch --job-name=ushcn --output=/home/yalavarthi/seperable_flows/results/ushcn/ushcn-mnf-ct-36-ft-0-711-%A.log --error=/home/yalavarthi/seperable_flows/results/ushcn/ushcn-mnf-ct-36-ft-0-711-%A.err --mail-type=FAIL --mail-user=yalavarthi@ismll.de /home/yalavarthi/seperable_flows/sbatch_file.sh train_mnf.py --batch-size 64 --epochs 1000 -lr 0.001 --dataset ushcn --n-gaussians 5 --flayers 3 --n-heads 2 --encoder grafiti --enc-layers 3 --n-hidden 32 -ct 36 -ft 0 --fold 0 
# sbatch --job-name=ushcn --output=/home/yalavarthi/seperable_flows/results/ushcn/ushcn-mnf-ct-36-ft-0-712-%A.log --error=/home/yalavarthi/seperable_flows/results/ushcn/ushcn-mnf-ct-36-ft-0-712-%A.err --mail-type=FAIL --mail-user=yalavarthi@ismll.de /home/yalavarthi/seperable_flows/sbatch_file.sh train_mnf.py --batch-size 64 --epochs 1000 -lr 0.001 --dataset ushcn --n-gaussians 5 --flayers 3 --n-heads 4 --encoder grafiti --enc-layers 3 --n-hidden 128 -ct 36 -ft 0 --fold 0 
# sbatch --job-name=ushcn --output=/home/yalavarthi/seperable_flows/results/ushcn/ushcn-mnf-ct-36-ft-0-713-%A.log --error=/home/yalavarthi/seperable_flows/results/ushcn/ushcn-mnf-ct-36-ft-0-713-%A.err --mail-type=FAIL --mail-user=yalavarthi@ismll.de /home/yalavarthi/seperable_flows/sbatch_file.sh train_mnf.py --batch-size 64 --epochs 1000 -lr 0.001 --dataset ushcn --n-gaussians 10 --flayers 3 --n-heads 2 --encoder grafiti --enc-layers 3 --n-hidden 32 -ct 36 -ft 0 --fold 0 
# sbatch --job-name=ushcn --output=/home/yalavarthi/seperable_flows/results/ushcn/ushcn-mnf-ct-36-ft-0-714-%A.log --error=/home/yalavarthi/seperable_flows/results/ushcn/ushcn-mnf-ct-36-ft-0-714-%A.err --mail-type=FAIL --mail-user=yalavarthi@ismll.de /home/yalavarthi/seperable_flows/sbatch_file.sh train_mnf.py --batch-size 64 --epochs 1000 -lr 0.001 --dataset ushcn --n-gaussians 3 --flayers 3 --n-heads 4 --encoder grafiti --enc-layers 4 --n-hidden 128 -ct 36 -ft 0 --fold 0 
# sbatch --job-name=ushcn --output=/home/yalavarthi/seperable_flows/results/ushcn/ushcn-mnf-ct-36-ft-0-715-%A.log --error=/home/yalavarthi/seperable_flows/results/ushcn/ushcn-mnf-ct-36-ft-0-715-%A.err --mail-type=FAIL --mail-user=yalavarthi@ismll.de /home/yalavarthi/seperable_flows/sbatch_file.sh train_mnf.py --batch-size 64 --epochs 1000 -lr 0.001 --dataset ushcn --n-gaussians 10 --flayers 3 --n-heads 4 --encoder grafiti --enc-layers 3 --n-hidden 64 -ct 36 -ft 0 --fold 0 
# sbatch --job-name=ushcn --output=/home/yalavarthi/seperable_flows/results/ushcn/ushcn-mnf-ct-36-ft-0-716-%A.log --error=/home/yalavarthi/seperable_flows/results/ushcn/ushcn-mnf-ct-36-ft-0-716-%A.err --mail-type=FAIL --mail-user=yalavarthi@ismll.de /home/yalavarthi/seperable_flows/sbatch_file.sh train_mnf.py --batch-size 64 --epochs 1000 -lr 0.001 --dataset ushcn --n-gaussians 7 --flayers 3 --n-heads 2 --encoder grafiti --enc-layers 4 --n-hidden 64 -ct 36 -ft 0 --fold 0 
# sbatch --job-name=ushcn --output=/home/yalavarthi/seperable_flows/results/ushcn/ushcn-mnf-ct-36-ft-0-717-%A.log --error=/home/yalavarthi/seperable_flows/results/ushcn/ushcn-mnf-ct-36-ft-0-717-%A.err --mail-type=FAIL --mail-user=yalavarthi@ismll.de /home/yalavarthi/seperable_flows/sbatch_file.sh train_mnf.py --batch-size 64 --epochs 1000 -lr 0.001 --dataset ushcn --n-gaussians 5 --flayers 3 --n-heads 2 --encoder grafiti --enc-layers 4 --n-hidden 128 -ct 36 -ft 0 --fold 0 
# sbatch --job-name=ushcn --output=/home/yalavarthi/seperable_flows/results/ushcn/ushcn-mnf-ct-36-ft-0-718-%A.log --error=/home/yalavarthi/seperable_flows/results/ushcn/ushcn-mnf-ct-36-ft-0-718-%A.err --mail-type=FAIL --mail-user=yalavarthi@ismll.de /home/yalavarthi/seperable_flows/sbatch_file.sh train_mnf.py --batch-size 64 --epochs 1000 -lr 0.001 --dataset ushcn --n-gaussians 1 --flayers 3 --n-heads 4 --encoder grafiti --enc-layers 4 --n-hidden 32 -ct 36 -ft 0 --fold 0 
# sbatch --job-name=ushcn --output=/home/yalavarthi/seperable_flows/results/ushcn/ushcn-mnf-ct-36-ft-0-719-%A.log --error=/home/yalavarthi/seperable_flows/results/ushcn/ushcn-mnf-ct-36-ft-0-719-%A.err --mail-type=FAIL --mail-user=yalavarthi@ismll.de /home/yalavarthi/seperable_flows/sbatch_file.sh train_mnf.py --batch-size 64 --epochs 1000 -lr 0.001 --dataset ushcn --n-gaussians 7 --flayers 3 --n-heads 2 --encoder grafiti --enc-layers 4 --n-hidden 128 -ct 36 -ft 0 --fold 0 
# sbatch --job-name=physionet2012 --output=/home/yalavarthi/seperable_flows/results/physionet2012/physionet2012-mnf-ct-36-ft-0-710-%A.log --error=/home/yalavarthi/seperable_flows/results/physionet2012/physionet2012-mnf-ct-36-ft-0-710-%A.err --mail-type=FAIL --mail-user=yalavarthi@ismll.de /home/yalavarthi/seperable_flows/sbatch_file.sh train_mnf.py --batch-size 64 --epochs 1000 -lr 0.001 --dataset physionet2012 --n-gaussians 7 --flayers 3 --n-heads 4 --encoder grafiti --enc-layers 4 --n-hidden 32 -ct 36 -ft 0 --fold 0 
# sbatch --job-name=physionet2012 --output=/home/yalavarthi/seperable_flows/results/physionet2012/physionet2012-mnf-ct-36-ft-0-711-%A.log --error=/home/yalavarthi/seperable_flows/results/physionet2012/physionet2012-mnf-ct-36-ft-0-711-%A.err --mail-type=FAIL --mail-user=yalavarthi@ismll.de /home/yalavarthi/seperable_flows/sbatch_file.sh train_mnf.py --batch-size 64 --epochs 1000 -lr 0.001 --dataset physionet2012 --n-gaussians 7 --flayers 3 --n-heads 2 --encoder grafiti --enc-layers 3 --n-hidden 128 -ct 36 -ft 0 --fold 0 
# sbatch --job-name=physionet2012 --output=/home/yalavarthi/seperable_flows/results/physionet2012/physionet2012-mnf-ct-36-ft-0-712-%A.log --error=/home/yalavarthi/seperable_flows/results/physionet2012/physionet2012-mnf-ct-36-ft-0-712-%A.err --mail-type=FAIL --mail-user=yalavarthi@ismll.de /home/yalavarthi/seperable_flows/sbatch_file.sh train_mnf.py --batch-size 64 --epochs 1000 -lr 0.001 --dataset physionet2012 --n-gaussians 7 --flayers 3 --n-heads 2 --encoder grafiti --enc-layers 4 --n-hidden 128 -ct 36 -ft 0 --fold 0 
# sbatch --job-name=physionet2012 --output=/home/yalavarthi/seperable_flows/results/physionet2012/physionet2012-mnf-ct-36-ft-0-713-%A.log --error=/home/yalavarthi/seperable_flows/results/physionet2012/physionet2012-mnf-ct-36-ft-0-713-%A.err --mail-type=FAIL --mail-user=yalavarthi@ismll.de /home/yalavarthi/seperable_flows/sbatch_file.sh train_mnf.py --batch-size 64 --epochs 1000 -lr 0.001 --dataset physionet2012 --n-gaussians 7 --flayers 3 --n-heads 2 --encoder grafiti --enc-layers 2 --n-hidden 32 -ct 36 -ft 0 --fold 0 
# sbatch --job-name=physionet2012 --output=/home/yalavarthi/seperable_flows/results/physionet2012/physionet2012-mnf-ct-36-ft-0-714-%A.log --error=/home/yalavarthi/seperable_flows/results/physionet2012/physionet2012-mnf-ct-36-ft-0-714-%A.err --mail-type=FAIL --mail-user=yalavarthi@ismll.de /home/yalavarthi/seperable_flows/sbatch_file.sh train_mnf.py --batch-size 64 --epochs 1000 -lr 0.001 --dataset physionet2012 --n-gaussians 3 --flayers 3 --n-heads 4 --encoder grafiti --enc-layers 3 --n-hidden 32 -ct 36 -ft 0 --fold 0 
# sbatch --job-name=physionet2012 --output=/home/yalavarthi/seperable_flows/results/physionet2012/physionet2012-mnf-ct-36-ft-0-715-%A.log --error=/home/yalavarthi/seperable_flows/results/physionet2012/physionet2012-mnf-ct-36-ft-0-715-%A.err --mail-type=FAIL --mail-user=yalavarthi@ismll.de /home/yalavarthi/seperable_flows/sbatch_file.sh train_mnf.py --batch-size 64 --epochs 1000 -lr 0.001 --dataset physionet2012 --n-gaussians 3 --flayers 3 --n-heads 1 --encoder grafiti --enc-layers 4 --n-hidden 32 -ct 36 -ft 0 --fold 0 
# sbatch --job-name=physionet2012 --output=/home/yalavarthi/seperable_flows/results/physionet2012/physionet2012-mnf-ct-36-ft-0-716-%A.log --error=/home/yalavarthi/seperable_flows/results/physionet2012/physionet2012-mnf-ct-36-ft-0-716-%A.err --mail-type=FAIL --mail-user=yalavarthi@ismll.de /home/yalavarthi/seperable_flows/sbatch_file.sh train_mnf.py --batch-size 64 --epochs 1000 -lr 0.001 --dataset physionet2012 --n-gaussians 10 --flayers 3 --n-heads 1 --encoder grafiti --enc-layers 3 --n-hidden 64 -ct 36 -ft 0 --fold 0 
# sbatch --job-name=physionet2012 --output=/home/yalavarthi/seperable_flows/results/physionet2012/physionet2012-mnf-ct-36-ft-0-717-%A.log --error=/home/yalavarthi/seperable_flows/results/physionet2012/physionet2012-mnf-ct-36-ft-0-717-%A.err --mail-type=FAIL --mail-user=yalavarthi@ismll.de /home/yalavarthi/seperable_flows/sbatch_file.sh train_mnf.py --batch-size 64 --epochs 1000 -lr 0.001 --dataset physionet2012 --n-gaussians 3 --flayers 3 --n-heads 2 --encoder grafiti --enc-layers 2 --n-hidden 64 -ct 36 -ft 0 --fold 0 
# sbatch --job-name=physionet2012 --output=/home/yalavarthi/seperable_flows/results/physionet2012/physionet2012-mnf-ct-36-ft-0-718-%A.log --error=/home/yalavarthi/seperable_flows/results/physionet2012/physionet2012-mnf-ct-36-ft-0-718-%A.err --mail-type=FAIL --mail-user=yalavarthi@ismll.de /home/yalavarthi/seperable_flows/sbatch_file.sh train_mnf.py --batch-size 64 --epochs 1000 -lr 0.001 --dataset physionet2012 --n-gaussians 10 --flayers 3 --n-heads 2 --encoder grafiti --enc-layers 4 --n-hidden 64 -ct 36 -ft 0 --fold 0 
# sbatch --job-name=physionet2012 --output=/home/yalavarthi/seperable_flows/results/physionet2012/physionet2012-mnf-ct-36-ft-0-719-%A.log --error=/home/yalavarthi/seperable_flows/results/physionet2012/physionet2012-mnf-ct-36-ft-0-719-%A.err --mail-type=FAIL --mail-user=yalavarthi@ismll.de /home/yalavarthi/seperable_flows/sbatch_file.sh train_mnf.py --batch-size 64 --epochs 1000 -lr 0.001 --dataset physionet2012 --n-gaussians 1 --flayers 3 --n-heads 1 --encoder grafiti --enc-layers 3 --n-hidden 128 -ct 36 -ft 0 --fold 0 
# sbatch --job-name=mimiciii --output=/home/yalavarthi/seperable_flows/results/mimiciii/mimiciii-mnf-ct-36-ft-0-710-%A.log --error=/home/yalavarthi/seperable_flows/results/mimiciii/mimiciii-mnf-ct-36-ft-0-710-%A.err --mail-type=FAIL --mail-user=yalavarthi@ismll.de /home/yalavarthi/seperable_flows/sbatch_file.sh train_mnf.py --batch-size 64 --epochs 1000 -lr 0.001 --dataset mimiciii --n-gaussians 5 --flayers 3 --n-heads 4 --encoder grafiti --enc-layers 2 --n-hidden 32 -ct 36 -ft 0 --fold 0 
# sbatch --job-name=mimiciii --output=/home/yalavarthi/seperable_flows/results/mimiciii/mimiciii-mnf-ct-36-ft-0-711-%A.log --error=/home/yalavarthi/seperable_flows/results/mimiciii/mimiciii-mnf-ct-36-ft-0-711-%A.err --mail-type=FAIL --mail-user=yalavarthi@ismll.de /home/yalavarthi/seperable_flows/sbatch_file.sh train_mnf.py --batch-size 64 --epochs 1000 -lr 0.001 --dataset mimiciii --n-gaussians 7 --flayers 3 --n-heads 1 --encoder grafiti --enc-layers 4 --n-hidden 128 -ct 36 -ft 0 --fold 0 
# sbatch --job-name=mimiciii --output=/home/yalavarthi/seperable_flows/results/mimiciii/mimiciii-mnf-ct-36-ft-0-712-%A.log --error=/home/yalavarthi/seperable_flows/results/mimiciii/mimiciii-mnf-ct-36-ft-0-712-%A.err --mail-type=FAIL --mail-user=yalavarthi@ismll.de /home/yalavarthi/seperable_flows/sbatch_file.sh train_mnf.py --batch-size 64 --epochs 1000 -lr 0.001 --dataset mimiciii --n-gaussians 1 --flayers 3 --n-heads 1 --encoder grafiti --enc-layers 3 --n-hidden 64 -ct 36 -ft 0 --fold 0 
# sbatch --job-name=mimiciii --output=/home/yalavarthi/seperable_flows/results/mimiciii/mimiciii-mnf-ct-36-ft-0-713-%A.log --error=/home/yalavarthi/seperable_flows/results/mimiciii/mimiciii-mnf-ct-36-ft-0-713-%A.err --mail-type=FAIL --mail-user=yalavarthi@ismll.de /home/yalavarthi/seperable_flows/sbatch_file.sh train_mnf.py --batch-size 64 --epochs 1000 -lr 0.001 --dataset mimiciii --n-gaussians 1 --flayers 3 --n-heads 2 --encoder grafiti --enc-layers 4 --n-hidden 32 -ct 36 -ft 0 --fold 0 
# sbatch --job-name=mimiciii --output=/home/yalavarthi/seperable_flows/results/mimiciii/mimiciii-mnf-ct-36-ft-0-714-%A.log --error=/home/yalavarthi/seperable_flows/results/mimiciii/mimiciii-mnf-ct-36-ft-0-714-%A.err --mail-type=FAIL --mail-user=yalavarthi@ismll.de /home/yalavarthi/seperable_flows/sbatch_file.sh train_mnf.py --batch-size 64 --epochs 1000 -lr 0.001 --dataset mimiciii --n-gaussians 1 --flayers 3 --n-heads 1 --encoder grafiti --enc-layers 4 --n-hidden 128 -ct 36 -ft 0 --fold 0 
# sbatch --job-name=mimiciii --output=/home/yalavarthi/seperable_flows/results/mimiciii/mimiciii-mnf-ct-36-ft-0-715-%A.log --error=/home/yalavarthi/seperable_flows/results/mimiciii/mimiciii-mnf-ct-36-ft-0-715-%A.err --mail-type=FAIL --mail-user=yalavarthi@ismll.de /home/yalavarthi/seperable_flows/sbatch_file.sh train_mnf.py --batch-size 64 --epochs 1000 -lr 0.001 --dataset mimiciii --n-gaussians 1 --flayers 3 --n-heads 1 --encoder grafiti --enc-layers 4 --n-hidden 64 -ct 36 -ft 0 --fold 0 
# sbatch --job-name=mimiciii --output=/home/yalavarthi/seperable_flows/results/mimiciii/mimiciii-mnf-ct-36-ft-0-716-%A.log --error=/home/yalavarthi/seperable_flows/results/mimiciii/mimiciii-mnf-ct-36-ft-0-716-%A.err --mail-type=FAIL --mail-user=yalavarthi@ismll.de /home/yalavarthi/seperable_flows/sbatch_file.sh train_mnf.py --batch-size 64 --epochs 1000 -lr 0.001 --dataset mimiciii --n-gaussians 7 --flayers 3 --n-heads 2 --encoder grafiti --enc-layers 3 --n-hidden 64 -ct 36 -ft 0 --fold 0 
# sbatch --job-name=mimiciii --output=/home/yalavarthi/seperable_flows/results/mimiciii/mimiciii-mnf-ct-36-ft-0-717-%A.log --error=/home/yalavarthi/seperable_flows/results/mimiciii/mimiciii-mnf-ct-36-ft-0-717-%A.err --mail-type=FAIL --mail-user=yalavarthi@ismll.de /home/yalavarthi/seperable_flows/sbatch_file.sh train_mnf.py --batch-size 64 --epochs 1000 -lr 0.001 --dataset mimiciii --n-gaussians 3 --flayers 3 --n-heads 2 --encoder grafiti --enc-layers 2 --n-hidden 32 -ct 36 -ft 0 --fold 0 
# sbatch --job-name=mimiciii --output=/home/yalavarthi/seperable_flows/results/mimiciii/mimiciii-mnf-ct-36-ft-0-718-%A.log --error=/home/yalavarthi/seperable_flows/results/mimiciii/mimiciii-mnf-ct-36-ft-0-718-%A.err --mail-type=FAIL --mail-user=yalavarthi@ismll.de /home/yalavarthi/seperable_flows/sbatch_file.sh train_mnf.py --batch-size 64 --epochs 1000 -lr 0.001 --dataset mimiciii --n-gaussians 7 --flayers 3 --n-heads 1 --encoder grafiti --enc-layers 4 --n-hidden 64 -ct 36 -ft 0 --fold 0 
# sbatch --job-name=mimiciii --output=/home/yalavarthi/seperable_flows/results/mimiciii/mimiciii-mnf-ct-36-ft-0-719-%A.log --error=/home/yalavarthi/seperable_flows/results/mimiciii/mimiciii-mnf-ct-36-ft-0-719-%A.err --mail-type=FAIL --mail-user=yalavarthi@ismll.de /home/yalavarthi/seperable_flows/sbatch_file.sh train_mnf.py --batch-size 64 --epochs 1000 -lr 0.001 --dataset mimiciii --n-gaussians 3 --flayers 3 --n-heads 4 --encoder grafiti --enc-layers 2 --n-hidden 128 -ct 36 -ft 0 --fold 0 
sbatch --job-name=mimiciv --output=/home/yalavarthi/seperable_flows/results/mimiciv/mimiciv-mnf-ct-36-ft-0-710-%A.log --error=/home/yalavarthi/seperable_flows/results/mimiciv/mimiciv-mnf-ct-36-ft-0-710-%A.err --mail-type=FAIL --mail-user=yalavarthi@ismll.de /home/yalavarthi/seperable_flows/sbatch_file.sh train_mnf.py --batch-size 64 --epochs 1000 -lr 0.001 --dataset mimiciv --n-gaussians 7 --flayers 3 --n-heads 4 --encoder grafiti --enc-layers 2 --n-hidden 128 -ct 36 -ft 0 --fold 0 
sbatch --job-name=mimiciv --output=/home/yalavarthi/seperable_flows/results/mimiciv/mimiciv-mnf-ct-36-ft-0-711-%A.log --error=/home/yalavarthi/seperable_flows/results/mimiciv/mimiciv-mnf-ct-36-ft-0-711-%A.err --mail-type=FAIL --mail-user=yalavarthi@ismll.de /home/yalavarthi/seperable_flows/sbatch_file.sh train_mnf.py --batch-size 64 --epochs 1000 -lr 0.001 --dataset mimiciv --n-gaussians 1 --flayers 3 --n-heads 2 --encoder grafiti --enc-layers 2 --n-hidden 64 -ct 36 -ft 0 --fold 0 
sbatch --job-name=mimiciv --output=/home/yalavarthi/seperable_flows/results/mimiciv/mimiciv-mnf-ct-36-ft-0-712-%A.log --error=/home/yalavarthi/seperable_flows/results/mimiciv/mimiciv-mnf-ct-36-ft-0-712-%A.err --mail-type=FAIL --mail-user=yalavarthi@ismll.de /home/yalavarthi/seperable_flows/sbatch_file.sh train_mnf.py --batch-size 64 --epochs 1000 -lr 0.001 --dataset mimiciv --n-gaussians 10 --flayers 3 --n-heads 2 --encoder grafiti --enc-layers 2 --n-hidden 128 -ct 36 -ft 0 --fold 0 
sbatch --job-name=mimiciv --output=/home/yalavarthi/seperable_flows/results/mimiciv/mimiciv-mnf-ct-36-ft-0-713-%A.log --error=/home/yalavarthi/seperable_flows/results/mimiciv/mimiciv-mnf-ct-36-ft-0-713-%A.err --mail-type=FAIL --mail-user=yalavarthi@ismll.de /home/yalavarthi/seperable_flows/sbatch_file.sh train_mnf.py --batch-size 64 --epochs 1000 -lr 0.001 --dataset mimiciv --n-gaussians 1 --flayers 3 --n-heads 4 --encoder grafiti --enc-layers 3 --n-hidden 32 -ct 36 -ft 0 --fold 0 
sbatch --job-name=mimiciv --output=/home/yalavarthi/seperable_flows/results/mimiciv/mimiciv-mnf-ct-36-ft-0-714-%A.log --error=/home/yalavarthi/seperable_flows/results/mimiciv/mimiciv-mnf-ct-36-ft-0-714-%A.err --mail-type=FAIL --mail-user=yalavarthi@ismll.de /home/yalavarthi/seperable_flows/sbatch_file.sh train_mnf.py --batch-size 64 --epochs 1000 -lr 0.001 --dataset mimiciv --n-gaussians 7 --flayers 3 --n-heads 2 --encoder grafiti --enc-layers 4 --n-hidden 64 -ct 36 -ft 0 --fold 0 
sbatch --job-name=mimiciv --output=/home/yalavarthi/seperable_flows/results/mimiciv/mimiciv-mnf-ct-36-ft-0-715-%A.log --error=/home/yalavarthi/seperable_flows/results/mimiciv/mimiciv-mnf-ct-36-ft-0-715-%A.err --mail-type=FAIL --mail-user=yalavarthi@ismll.de /home/yalavarthi/seperable_flows/sbatch_file.sh train_mnf.py --batch-size 64 --epochs 1000 -lr 0.001 --dataset mimiciv --n-gaussians 1 --flayers 3 --n-heads 1 --encoder grafiti --enc-layers 3 --n-hidden 32 -ct 36 -ft 0 --fold 0 
sbatch --job-name=mimiciv --output=/home/yalavarthi/seperable_flows/results/mimiciv/mimiciv-mnf-ct-36-ft-0-716-%A.log --error=/home/yalavarthi/seperable_flows/results/mimiciv/mimiciv-mnf-ct-36-ft-0-716-%A.err --mail-type=FAIL --mail-user=yalavarthi@ismll.de /home/yalavarthi/seperable_flows/sbatch_file.sh train_mnf.py --batch-size 64 --epochs 1000 -lr 0.001 --dataset mimiciv --n-gaussians 7 --flayers 3 --n-heads 1 --encoder grafiti --enc-layers 4 --n-hidden 64 -ct 36 -ft 0 --fold 0 
sbatch --job-name=mimiciv --output=/home/yalavarthi/seperable_flows/results/mimiciv/mimiciv-mnf-ct-36-ft-0-717-%A.log --error=/home/yalavarthi/seperable_flows/results/mimiciv/mimiciv-mnf-ct-36-ft-0-717-%A.err --mail-type=FAIL --mail-user=yalavarthi@ismll.de /home/yalavarthi/seperable_flows/sbatch_file.sh train_mnf.py --batch-size 64 --epochs 1000 -lr 0.001 --dataset mimiciv --n-gaussians 10 --flayers 3 --n-heads 2 --encoder grafiti --enc-layers 4 --n-hidden 32 -ct 36 -ft 0 --fold 0 
sbatch --job-name=mimiciv --output=/home/yalavarthi/seperable_flows/results/mimiciv/mimiciv-mnf-ct-36-ft-0-718-%A.log --error=/home/yalavarthi/seperable_flows/results/mimiciv/mimiciv-mnf-ct-36-ft-0-718-%A.err --mail-type=FAIL --mail-user=yalavarthi@ismll.de /home/yalavarthi/seperable_flows/sbatch_file.sh train_mnf.py --batch-size 64 --epochs 1000 -lr 0.001 --dataset mimiciv --n-gaussians 5 --flayers 3 --n-heads 1 --encoder grafiti --enc-layers 4 --n-hidden 64 -ct 36 -ft 0 --fold 0 
sbatch --job-name=mimiciv --output=/home/yalavarthi/seperable_flows/results/mimiciv/mimiciv-mnf-ct-36-ft-0-719-%A.log --error=/home/yalavarthi/seperable_flows/results/mimiciv/mimiciv-mnf-ct-36-ft-0-719-%A.err --mail-type=FAIL --mail-user=yalavarthi@ismll.de /home/yalavarthi/seperable_flows/sbatch_file.sh train_mnf.py --batch-size 64 --epochs 1000 -lr 0.001 --dataset mimiciv --n-gaussians 10 --flayers 3 --n-heads 4 --encoder grafiti --enc-layers 2 --n-hidden 32 -ct 36 -ft 0 --fold 0 

