
# # USHCN
# sbatch --job-name=ushcn-only-marg-results --output=/home/yalavarthi/seperable_flows/sanity_results/ushcn/ushcn-mnf-wd-ct-36-ft-0-510-%A.log --error=/home/yalavarthi/seperable_flows/sanity_results/ushcn/ushcn-mnf-wd-ct-36-ft-0-510-%A.err --mail-type=FAIL --mail-user=yalavarthi@ismll.de /home/yalavarthi/seperable_flows/sbatch_file.sh train_mnf.py --batch-size 64 --epochs 1000 -lr 0.001 --dataset ushcn --n-gaussians 7  --flayers 3 --n-heads 2 --n-hidden 64  -ct 36 -ft 0 --fold 0

# sbatch --job-name=ushcn-only-marg-results --output=/home/yalavarthi/seperable_flows/sanity_results/ushcn/ushcn-mnf-wd-ct-36-ft-0-511-%A.log --error=/home/yalavarthi/seperable_flows/sanity_results/ushcn/ushcn-mnf-wd-ct-36-ft-0-511-%A.err --mail-type=FAIL --mail-user=yalavarthi@ismll.de /home/yalavarthi/seperable_flows/sbatch_file.sh train_mnf.py --batch-size 64 --epochs 1000 -lr 0.001 --dataset ushcn --n-gaussians 7  --flayers 3 --n-heads 2 --n-hidden 64 -ct 36 -ft 0 --fold 1

# sbatch --job-name=ushcn-only-marg-results --output=/home/yalavarthi/seperable_flows/sanity_results/ushcn/ushcn-mnf-wd-ct-36-ft-0-512-%A.log --error=/home/yalavarthi/seperable_flows/sanity_results/ushcn/ushcn-mnf-wd-ct-36-ft-0-512-%A.err --mail-type=FAIL --mail-user=yalavarthi@ismll.de /home/yalavarthi/seperable_flows/sbatch_file.sh train_mnf.py --batch-size 64 --epochs 1000 -lr 0.001 --dataset ushcn --n-gaussians 7  --flayers 3 --n-heads 2 --n-hidden 64 -ct 36 -ft 0 --fold 2

# sbatch --job-name=ushcn-only-marg-results --output=/home/yalavarthi/seperable_flows/sanity_results/ushcn/ushcn-mnf-wd-ct-36-ft-0-513-%A.log --error=/home/yalavarthi/seperable_flows/sanity_results/ushcn/ushcn-mnf-wd-ct-36-ft-0-513-%A.err --mail-type=FAIL --mail-user=yalavarthi@ismll.de /home/yalavarthi/seperable_flows/sbatch_file.sh train_mnf.py --batch-size 64 --epochs 1000 -lr 0.001 --dataset ushcn --n-gaussians 7  --flayers 3 --n-heads 2 --n-hidden 64 -ct 36 -ft 0 --fold 3

# sbatch --job-name=ushcn-only-marg-results --output=/home/yalavarthi/seperable_flows/sanity_results/ushcn/ushcn-mnf-wd-ct-36-ft-0-514-%A.log --error=/home/yalavarthi/seperable_flows/sanity_results/ushcn/ushcn-mnf-wd-ct-36-ft-0-514-%A.err --mail-type=FAIL --mail-user=yalavarthi@ismll.de /home/yalavarthi/seperable_flows/sbatch_file.sh train_mnf.py --batch-size 64 --epochs 1000 -lr 0.001 --dataset ushcn --n-gaussians 7  --flayers 3 --n-heads 2 --n-hidden 64 -ct 36 -ft 0 --fold 4



sbatch --job-name=physionet2012-only-marg-results --output=/home/yalavarthi/seperable_flows/sanity_results/physionet2012/physionet2012-mnf-wd-ct-36-ft-0-510-%A.log --error=/home/yalavarthi/seperable_flows/sanity_results/physionet2012/physionet2012-mnf-wd-ct-36-ft-0-510-%A.err --mail-type=FAIL --mail-user=yalavarthi@ismll.de /home/yalavarthi/seperable_flows/sbatch_file.sh train_mnf.py --batch-size 64 --epochs 1000 -lr 0.001 --dataset physionet2012 --n-gaussians 10 --flayers 3 --n-heads 1 --n-hidden 64 -ct 36 -ft 0 --fold 0

sbatch --job-name=physionet2012-only-marg-results --output=/home/yalavarthi/seperable_flows/sanity_results/physionet2012/physionet2012-mnf-wd-ct-36-ft-0-511-%A.log --error=/home/yalavarthi/seperable_flows/sanity_results/physionet2012/physionet2012-mnf-wd-ct-36-ft-0-511-%A.err --mail-type=FAIL --mail-user=yalavarthi@ismll.de /home/yalavarthi/seperable_flows/sbatch_file.sh train_mnf.py --batch-size 64 --epochs 1000 -lr 0.001 --dataset physionet2012 --n-gaussians 10 --flayers 3 --n-heads 1 --n-hidden 64 -ct 36 -ft 0 --fold 1

sbatch --job-name=physionet2012-only-marg-results --output=/home/yalavarthi/seperable_flows/sanity_results/physionet2012/physionet2012-mnf-wd-ct-36-ft-0-512-%A.log --error=/home/yalavarthi/seperable_flows/sanity_results/physionet2012/physionet2012-mnf-wd-ct-36-ft-0-512-%A.err --mail-type=FAIL --mail-user=yalavarthi@ismll.de /home/yalavarthi/seperable_flows/sbatch_file.sh train_mnf.py --batch-size 64 --epochs 1000 -lr 0.001 --dataset physionet2012 --n-gaussians 10 --flayers 3 --n-heads 1 --n-hidden 64 -ct 36 -ft 0 --fold 2

sbatch --job-name=physionet2012-only-marg-results --output=/home/yalavarthi/seperable_flows/sanity_results/physionet2012/physionet2012-mnf-wd-ct-36-ft-0-513-%A.log --error=/home/yalavarthi/seperable_flows/sanity_results/physionet2012/physionet2012-mnf-wd-ct-36-ft-0-513-%A.err --mail-type=FAIL --mail-user=yalavarthi@ismll.de /home/yalavarthi/seperable_flows/sbatch_file.sh train_mnf.py --batch-size 64 --epochs 1000 -lr 0.001 --dataset physionet2012 --n-gaussians 10 --flayers 3 --n-heads 1 --n-hidden 64 -ct 36 -ft 0 --fold 3

sbatch --job-name=physionet2012-only-marg-results --output=/home/yalavarthi/seperable_flows/sanity_results/physionet2012/physionet2012-mnf-wd-ct-36-ft-0-514-%A.log --error=/home/yalavarthi/seperable_flows/sanity_results/physionet2012/physionet2012-mnf-wd-ct-36-ft-0-514-%A.err --mail-type=FAIL --mail-user=yalavarthi@ismll.de /home/yalavarthi/seperable_flows/sbatch_file.sh train_mnf.py --batch-size 64 --epochs 1000 -lr 0.001 --dataset physionet2012 --n-gaussians 10 --flayers 3 --n-heads 1 --n-hidden 64 -ct 36 -ft 0 --fold 4
