sbatch --job-name=mimiciv --output=/home/yalavarthi/seperable_flows/results/var_d/mimiciv-mnf-ct-12-ft-36-%A.log --error=/home/yalavarthi/seperable_flows/results/var_d/mimiciv-mnf-ct-12-ft-36-%A.err --mail-type=FAIL --mail-user=yalavarthi@ismll.de /home/yalavarthi/seperable_flows/sbatch_file.sh temp_ablation.py --batch-size 64 --epochs 1 -lr 0.001 --dataset mimiciv --n-gaussians 10 --flayers 3 --n-heads 2 --n-hidden 128 -ct 12 -ft 36 --fold 0

sbatch --job-name=mimiciv --output=/home/yalavarthi/seperable_flows/results/var_d/mimiciv-mnf-ct-12-ft-36-%A.log --error=/home/yalavarthi/seperable_flows/results/var_d/mimiciv-mnf-ct-12-ft-36-%A.err --mail-type=FAIL --mail-user=yalavarthi@ismll.de /home/yalavarthi/seperable_flows/sbatch_file.sh temp_ablation.py --batch-size 64 --epochs 1 -lr 0.001 --dataset mimiciv --n-gaussians 7 --flayers 3 --n-heads 2 --n-hidden 128 -ct 12 -ft 36 --fold 0

sbatch --job-name=mimiciv --output=/home/yalavarthi/seperable_flows/results/var_d/mimiciv-mnf-ct-12-ft-36-%A.log --error=/home/yalavarthi/seperable_flows/results/var_d/mimiciv-mnf-ct-12-ft-36-%A.err --mail-type=FAIL --mail-user=yalavarthi@ismll.de /home/yalavarthi/seperable_flows/sbatch_file.sh temp_ablation.py --batch-size 64 --epochs 1 -lr 0.001 --dataset mimiciv --n-gaussians 5 --flayers 3 --n-heads 2 --n-hidden 128 -ct 12 -ft 36 --fold 0

sbatch --job-name=mimiciv --output=/home/yalavarthi/seperable_flows/results/var_d/mimiciv-mnf-ct-12-ft-36-%A.log --error=/home/yalavarthi/seperable_flows/results/var_d/mimiciv-mnf-ct-12-ft-36-%A.err --mail-type=FAIL --mail-user=yalavarthi@ismll.de /home/yalavarthi/seperable_flows/sbatch_file.sh temp_ablation.py --batch-size 64 --epochs 1 -lr 0.001 --dataset mimiciv --n-gaussians 3 --flayers 3 --n-heads 2 --n-hidden 128 -ct 12 -ft 36 --fold 0

sbatch --job-name=mimiciv --output=/home/yalavarthi/seperable_flows/results/var_d/mimiciv-mnf-ct-12-ft-36-%A.log --error=/home/yalavarthi/seperable_flows/results/var_d/mimiciv-mnf-ct-12-ft-36-%A.err --mail-type=FAIL --mail-user=yalavarthi@ismll.de /home/yalavarthi/seperable_flows/sbatch_file.sh temp_ablation.py --batch-size 64 --epochs 1 -lr 0.001 --dataset mimiciv --n-gaussians 1 --flayers 3 --n-heads 2 --n-hidden 128 -ct 12 -ft 36 --fold 0

sbatch --job-name=mimiciii --output=/home/yalavarthi/seperable_flows/results/var_d/mimiciii-mnf-ct-12-ft-36-%A.log --error=/home/yalavarthi/seperable_flows/results/var_d/mimiciii-mnf-ct-12-ft-36-%A.err --mail-type=FAIL --mail-user=yalavarthi@ismll.de /home/yalavarthi/seperable_flows/sbatch_file.sh temp_ablation.py --batch-size 64 --epochs 1 -lr 0.001 --dataset mimiciii --n-gaussians 10 --flayers 3 --n-heads 2 --n-hidden 128 -ct 12 -ft 36 --fold 0

sbatch --job-name=mimiciii --output=/home/yalavarthi/seperable_flows/results/var_d/mimiciii-mnf-ct-12-ft-36-%A.log --error=/home/yalavarthi/seperable_flows/results/var_d/mimiciii-mnf-ct-12-ft-36-%A.err --mail-type=FAIL --mail-user=yalavarthi@ismll.de /home/yalavarthi/seperable_flows/sbatch_file.sh temp_ablation.py --batch-size 64 --epochs 1 -lr 0.001 --dataset mimiciii --n-gaussians 7 --flayers 3 --n-heads 2 --n-hidden 128 -ct 12 -ft 36 --fold 0

sbatch --job-name=mimiciii --output=/home/yalavarthi/seperable_flows/results/var_d/mimiciii-mnf-ct-12-ft-36-%A.log --error=/home/yalavarthi/seperable_flows/results/var_d/mimiciii-mnf-ct-12-ft-36-%A.err --mail-type=FAIL --mail-user=yalavarthi@ismll.de /home/yalavarthi/seperable_flows/sbatch_file.sh temp_ablation.py --batch-size 64 --epochs 1 -lr 0.001 --dataset mimiciii --n-gaussians 5 --flayers 3 --n-heads 2 --n-hidden 128 -ct 12 -ft 36 --fold 0

sbatch --job-name=mimiciii --output=/home/yalavarthi/seperable_flows/results/var_d/mimiciii-mnf-ct-12-ft-36-%A.log --error=/home/yalavarthi/seperable_flows/results/var_d/mimiciii-mnf-ct-12-ft-36-%A.err --mail-type=FAIL --mail-user=yalavarthi@ismll.de /home/yalavarthi/seperable_flows/sbatch_file.sh temp_ablation.py --batch-size 64 --epochs 1 -lr 0.001 --dataset mimiciii --n-gaussians 3 --flayers 3 --n-heads 2 --n-hidden 128 -ct 12 -ft 36 --fold 0

sbatch --job-name=mimiciii --output=/home/yalavarthi/seperable_flows/results/var_d/mimiciii-mnf-ct-12-ft-36-%A.log --error=/home/yalavarthi/seperable_flows/results/var_d/mimiciii-mnf-ct-12-ft-36-%A.err --mail-type=FAIL --mail-user=yalavarthi@ismll.de /home/yalavarthi/seperable_flows/sbatch_file.sh temp_ablation.py --batch-size 64 --epochs 1 -lr 0.001 --dataset mimiciii --n-gaussians 1 --flayers 3 --n-heads 2 --n-hidden 128 -ct 12 -ft 36 --fold 0

sbatch --job-name=physionet2012 --output=/home/yalavarthi/seperable_flows/results/var_d/physionet2012-mnf-ct-12-ft-36-%A.log --error=/home/yalavarthi/seperable_flows/results/var_d/physionet2012-mnf-ct-12-ft-36-%A.err --mail-type=FAIL --mail-user=yalavarthi@ismll.de /home/yalavarthi/seperable_flows/sbatch_file.sh temp_ablation.py --batch-size 64 --epochs 1 -lr 0.001 --dataset physionet2012 --n-gaussians 10 --flayers 3 --n-heads 2 --n-hidden 128 -ct 12 -ft 36 --fold 0

sbatch --job-name=physionet2012 --output=/home/yalavarthi/seperable_flows/results/var_d/physionet2012-mnf-ct-12-ft-36-%A.log --error=/home/yalavarthi/seperable_flows/results/var_d/physionet2012-mnf-ct-12-ft-36-%A.err --mail-type=FAIL --mail-user=yalavarthi@ismll.de /home/yalavarthi/seperable_flows/sbatch_file.sh temp_ablation.py --batch-size 64 --epochs 1 -lr 0.001 --dataset physionet2012 --n-gaussians 7 --flayers 3 --n-heads 2 --n-hidden 128 -ct 12 -ft 36 --fold 0

sbatch --job-name=physionet2012 --output=/home/yalavarthi/seperable_flows/results/var_d/physionet2012-mnf-ct-12-ft-36-%A.log --error=/home/yalavarthi/seperable_flows/results/var_d/physionet2012-mnf-ct-12-ft-36-%A.err --mail-type=FAIL --mail-user=yalavarthi@ismll.de /home/yalavarthi/seperable_flows/sbatch_file.sh temp_ablation.py --batch-size 64 --epochs 1 -lr 0.001 --dataset physionet2012 --n-gaussians 5 --flayers 3 --n-heads 2 --n-hidden 128 -ct 12 -ft 36 --fold 0

sbatch --job-name=physionet2012 --output=/home/yalavarthi/seperable_flows/results/var_d/physionet2012-mnf-ct-12-ft-36-%A.log --error=/home/yalavarthi/seperable_flows/results/var_d/physionet2012-mnf-ct-12-ft-36-%A.err --mail-type=FAIL --mail-user=yalavarthi@ismll.de /home/yalavarthi/seperable_flows/sbatch_file.sh temp_ablation.py --batch-size 64 --epochs 1 -lr 0.001 --dataset physionet2012 --n-gaussians 3 --flayers 3 --n-heads 2 --n-hidden 128 -ct 12 -ft 36 --fold 0

sbatch --job-name=physionet2012 --output=/home/yalavarthi/seperable_flows/results/var_d/physionet2012-mnf-ct-12-ft-36-%A.log --error=/home/yalavarthi/seperable_flows/results/var_d/physionet2012-mnf-ct-12-ft-36-%A.err --mail-type=FAIL --mail-user=yalavarthi@ismll.de /home/yalavarthi/seperable_flows/sbatch_file.sh temp_ablation.py --batch-size 64 --epochs 1 -lr 0.001 --dataset physionet2012 --n-gaussians 1 --flayers 3 --n-heads 2 --n-hidden 128 -ct 12 -ft 36 --fold 0

sbatch --job-name=ushcn --output=/home/yalavarthi/seperable_flows/results/var_d/ushcn-mnf-ct-12-ft-36-%A.log --error=/home/yalavarthi/seperable_flows/results/var_d/ushcn-mnf-ct-12-ft-36-%A.err --mail-type=FAIL --mail-user=yalavarthi@ismll.de /home/yalavarthi/seperable_flows/sbatch_file.sh temp_ablation.py --batch-size 64 --epochs 1 -lr 0.001 --dataset ushcn --n-gaussians 10 --flayers 3 --n-heads 2 --n-hidden 128 -ct 12 -ft 36 --fold 0

sbatch --job-name=ushcn --output=/home/yalavarthi/seperable_flows/results/var_d/ushcn-mnf-ct-12-ft-36-%A.log --error=/home/yalavarthi/seperable_flows/results/var_d/ushcn-mnf-ct-12-ft-36-%A.err --mail-type=FAIL --mail-user=yalavarthi@ismll.de /home/yalavarthi/seperable_flows/sbatch_file.sh temp_ablation.py --batch-size 64 --epochs 1 -lr 0.001 --dataset ushcn --n-gaussians 7 --flayers 3 --n-heads 2 --n-hidden 128 -ct 12 -ft 36 --fold 0

sbatch --job-name=ushcn --output=/home/yalavarthi/seperable_flows/results/var_d/ushcn-mnf-ct-12-ft-36-%A.log --error=/home/yalavarthi/seperable_flows/results/var_d/ushcn-mnf-ct-12-ft-36-%A.err --mail-type=FAIL --mail-user=yalavarthi@ismll.de /home/yalavarthi/seperable_flows/sbatch_file.sh temp_ablation.py --batch-size 64 --epochs 1 -lr 0.001 --dataset ushcn --n-gaussians 5 --flayers 3 --n-heads 2 --n-hidden 128 -ct 12 -ft 36 --fold 0

sbatch --job-name=ushcn --output=/home/yalavarthi/seperable_flows/results/var_d/ushcn-mnf-ct-12-ft-36-%A.log --error=/home/yalavarthi/seperable_flows/results/var_d/ushcn-mnf-ct-12-ft-36-%A.err --mail-type=FAIL --mail-user=yalavarthi@ismll.de /home/yalavarthi/seperable_flows/sbatch_file.sh temp_ablation.py --batch-size 64 --epochs 1 -lr 0.001 --dataset ushcn --n-gaussians 3 --flayers 3 --n-heads 2 --n-hidden 128 -ct 12 -ft 36 --fold 0

sbatch --job-name=ushcn --output=/home/yalavarthi/seperable_flows/results/var_d/ushcn-mnf-ct-12-ft-36-%A.log --error=/home/yalavarthi/seperable_flows/results/var_d/ushcn-mnf-ct-12-ft-36-%A.err --mail-type=FAIL --mail-user=yalavarthi@ismll.de /home/yalavarthi/seperable_flows/sbatch_file.sh temp_ablation.py --batch-size 64 --epochs 1 -lr 0.001 --dataset ushcn --n-gaussians 1 --flayers 3 --n-heads 2 --n-hidden 128 -ct 12 -ft 36 --fold 0