sbatch --job-name=mimiciv --output=/home/yalavarthi/seperable_flows/results/var_k/mimiciv-mnf-ct-36-ft-12-%A.log --error=/home/yalavarthi/seperable_flows/results/var_k/mimiciv-mnf-ct-36-ft-12-%A.err --mail-type=FAIL --mail-user=yalavarthi@ismll.de /home/yalavarthi/seperable_flows/sbatch_file.sh temp_ablation.py --batch-size 64 --epochs 1 -lr 0.001 --dataset mimiciv --n-gaussians 10 --flayers 3 --n-heads 2 --n-hidden 128 -ct 36 -ft 12 --fold 0

sbatch --job-name=mimiciv --output=/home/yalavarthi/seperable_flows/results/var_k/mimiciv-mnf-ct-24-ft-24-%A.log --error=/home/yalavarthi/seperable_flows/results/var_k/mimiciv-mnf-ct-24-ft-24-%A.err --mail-type=FAIL --mail-user=yalavarthi@ismll.de /home/yalavarthi/seperable_flows/sbatch_file.sh temp_ablation.py --batch-size 64 --epochs 1 -lr 0.001 --dataset mimiciv --n-gaussians 10 --flayers 3 --n-heads 2 --n-hidden 128 -ct 24 -ft 24 --fold 0

sbatch --job-name=mimiciv --output=/home/yalavarthi/seperable_flows/results/var_k/mimiciv-mnf-ct-12-ft-36-%A.log --error=/home/yalavarthi/seperable_flows/results/var_k/mimiciv-mnf-ct-12-ft-36-%A.err --mail-type=FAIL --mail-user=yalavarthi@ismll.de /home/yalavarthi/seperable_flows/sbatch_file.sh temp_ablation.py --batch-size 64 --epochs 1 -lr 0.001 --dataset mimiciv --n-gaussians 10 --flayers 3 --n-heads 2 --n-hidden 128 -ct 12 -ft 36 --fold 0

sbatch --job-name=mimiciii --output=/home/yalavarthi/seperable_flows/results/var_k/mimiciii-mnf-ct-36-ft-12-%A.log --error=/home/yalavarthi/seperable_flows/results/var_k/mimiciii-mnf-ct-36-ft-12-%A.err --mail-type=FAIL --mail-user=yalavarthi@ismll.de /home/yalavarthi/seperable_flows/sbatch_file.sh temp_ablation.py --batch-size 64 --epochs 1 -lr 0.001 --dataset mimiciii --n-gaussians 10 --flayers 3 --n-heads 2 --n-hidden 128 -ct 36 -ft 12 --fold 0

sbatch --job-name=mimiciii --output=/home/yalavarthi/seperable_flows/results/var_k/mimiciii-mnf-ct-24-ft-24-%A.log --error=/home/yalavarthi/seperable_flows/results/var_k/mimiciii-mnf-ct-24-ft-24-%A.err --mail-type=FAIL --mail-user=yalavarthi@ismll.de /home/yalavarthi/seperable_flows/sbatch_file.sh temp_ablation.py --batch-size 64 --epochs 1 -lr 0.001 --dataset mimiciii --n-gaussians 10 --flayers 3 --n-heads 2 --n-hidden 128 -ct 24 -ft 24 --fold 0

sbatch --job-name=mimiciii --output=/home/yalavarthi/seperable_flows/results/var_k/mimiciii-mnf-ct-12-ft-36-%A.log --error=/home/yalavarthi/seperable_flows/results/var_k/mimiciii-mnf-ct-12-ft-36-%A.err --mail-type=FAIL --mail-user=yalavarthi@ismll.de /home/yalavarthi/seperable_flows/sbatch_file.sh temp_ablation.py --batch-size 64 --epochs 1 -lr 0.001 --dataset mimiciii --n-gaussians 10 --flayers 3 --n-heads 2 --n-hidden 128 -ct 12 -ft 36 --fold 0

sbatch --job-name=physionet2012 --output=/home/yalavarthi/seperable_flows/results/var_k/physionet2012-mnf-ct-36-ft-12-%A.log --error=/home/yalavarthi/seperable_flows/results/var_k/physionet2012-mnf-ct-36-ft-12-%A.err --mail-type=FAIL --mail-user=yalavarthi@ismll.de /home/yalavarthi/seperable_flows/sbatch_file.sh temp_ablation.py --batch-size 64 --epochs 1 -lr 0.001 --dataset physionet2012 --n-gaussians 10 --flayers 3 --n-heads 2 --n-hidden 128 -ct 36 -ft 12 --fold 0

sbatch --job-name=physionet2012 --output=/home/yalavarthi/seperable_flows/results/var_k/physionet2012-mnf-ct-24-ft-24-%A.log --error=/home/yalavarthi/seperable_flows/results/var_k/physionet2012-mnf-ct-24-ft-24-%A.err --mail-type=FAIL --mail-user=yalavarthi@ismll.de /home/yalavarthi/seperable_flows/sbatch_file.sh temp_ablation.py --batch-size 64 --epochs 1 -lr 0.001 --dataset physionet2012 --n-gaussians 10 --flayers 3 --n-heads 2 --n-hidden 128 -ct 24 -ft 24 --fold 0

sbatch --job-name=physionet2012 --output=/home/yalavarthi/seperable_flows/results/var_k/physionet2012-mnf-ct-12-ft-36-%A.log --error=/home/yalavarthi/seperable_flows/results/var_k/physionet2012-mnf-ct-12-ft-36-%A.err --mail-type=FAIL --mail-user=yalavarthi@ismll.de /home/yalavarthi/seperable_flows/sbatch_file.sh temp_ablation.py --batch-size 64 --epochs 1 -lr 0.001 --dataset physionet2012 --n-gaussians 10 --flayers 3 --n-heads 2 --n-hidden 128 -ct 12 -ft 36 --fold 0

sbatch --job-name=ushcn --output=/home/yalavarthi/seperable_flows/results/var_k/ushcn-mnf-ct-36-ft-12-%A.log --error=/home/yalavarthi/seperable_flows/results/var_k/ushcn-mnf-ct-36-ft-12-%A.err --mail-type=FAIL --mail-user=yalavarthi@ismll.de /home/yalavarthi/seperable_flows/sbatch_file.sh temp_ablation.py --batch-size 64 --epochs 1 -lr 0.001 --dataset ushcn --n-gaussians 10 --flayers 3 --n-heads 2 --n-hidden 128 -ct 36 -ft 12 --fold 0

sbatch --job-name=ushcn --output=/home/yalavarthi/seperable_flows/results/var_k/ushcn-mnf-ct-24-ft-24-%A.log --error=/home/yalavarthi/seperable_flows/results/var_k/ushcn-mnf-ct-24-ft-24-%A.err --mail-type=FAIL --mail-user=yalavarthi@ismll.de /home/yalavarthi/seperable_flows/sbatch_file.sh temp_ablation.py --batch-size 64 --epochs 1 -lr 0.001 --dataset ushcn --n-gaussians 10 --flayers 3 --n-heads 2 --n-hidden 128 -ct 24 -ft 24 --fold 0

sbatch --job-name=ushcn --output=/home/yalavarthi/seperable_flows/results/var_k/ushcn-mnf-ct-12-ft-36-%A.log --error=/home/yalavarthi/seperable_flows/results/var_k/ushcn-mnf-ct-12-ft-36-%A.err --mail-type=FAIL --mail-user=yalavarthi@ismll.de /home/yalavarthi/seperable_flows/sbatch_file.sh temp_ablation.py --batch-size 64 --epochs 1 -lr 0.001 --dataset ushcn --n-gaussians 10 --flayers 3 --n-heads 2 --n-hidden 128 -ct 12 -ft 36 --fold 0